#ifndef __IO_REGS_H__
#define __IO_REGS_H__

#define IOREG_SB   0xFF01
#define IOREG_SC   0xFF02
#define IOREG_DIV  0xFF04
#define IOREG_TIMA 0xFF05
#define IOREG_TMA  0xFF06
#define IOREG_TAC  0xFF07
#define IOREG_IF   0xFF0F
#define IOREG_LCDC 0xFF40
#define IOREG_STAT 0xFF41
#define IOREG_SCY  0xFF42
#define IOREG_SCX  0xFF43
#define IOREG_LY   0xFF44
#define IOREG_LYC  0xFF45
#define IOREG_BGP  0xFF47
#define IOREG_OBP0 0xFF48
#define IOREG_OBP1 0xFF49
#define IOREG_WY   0xFF4A
#define IOREG_WX   0xFF4B
#define IOREG_IE   0xFFFF

#define IOREG_TAC_STOP_MASK      0x04
#define IOREG_TAC_CLOCK_SEL_MASK 0x03
#define IOREG_TAC_STOP           0x00
#define IOREG_TAC_START          0x04
#define IOREG_TAC_CLOCK_4_KHZ    0x00
#define IOREG_TAC_CLOCK_256_KHZ  0x01
#define IOREG_TAC_CLOCK_64_KHZ   0x02
#define IOREG_TAC_CLOCK_16_KHZ   0x03


// LCDC Values
#define IOREG_LCDC_ENABLE_MASK   0x80
#define IOREG_LCDC_ENABLE        0x80
#define IOREG_LCDC_DIABLE        0x00

#define IOREG_LCDC_WIN_TILE_MAP_SEL_MASK 0x40
#define IOREG_LCDC_WIN_TILE_MAP_SEL_9800 0x00
#define IOREG_LCDC_WIN_TILE_MAP_SEL_9C00 0x40

#define IOREG_LCDC_WIN_DISPLAY_MASK 0x20
#define IOREG_LCDC_WIN_DISPLAY_ON   0x20
#define IOREG_LCDC_WIN_DISPLAY_OFF  0x00

#define IOREG_LCDC_TILE_DATA_SEL_MASK 0x10
#define IOREG_LCDC_TILE_DATA_SEL_8000 0x10
#define IOREG_LCDC_TILE_DATA_SEL_8800 0x00

#define IOREG_LCDC_BG_TILE_MAP_SEL_MASK 0x08
#define IOREG_LCDC_BG_TILE_MAP_SEL_9800 0x00
#define IOREG_LCDC_BG_TILE_MAP_SEL_9C00 0x08

#define IOREG_LCDC_OBJ_SIZE_MASK 0x04
#define IOREG_LCDC_OBJ_SIZE_8_16 0x04
#define IOREG_LCDC_OBJ_SIZE_8_8 0x00

#define IOREG_LCDC_OBJ_DISPLAY_MASK 0x02
#define IOREG_LCDC_OBJ_DISPLAY_ON   0x02
#define IOREG_LCDC_OBJ_DISPLAY_OFF  0x00

//TODO Redefine the meaning of this register for CGB
#define IOREG_LCDC_BG_DISPLAY_MASK  0x01
#define IOREG_LCDC_BG_DISPLAY_ON    0x01
#define IOREG_LCDC_BG_DISPLAY_OFF   0x00


// STAT Values
#define IOREG_STAT_COINCIDENCE_INTR 0x40
#define IOREG_STAT_MODE_2_OAM_INTR 0x20
#define IOREG_STAT_MODE_1_VBLANK_INTR 0x10
#define IOREG_STAT_MODE_0_HBLANK_INTR 0x08
#define IOREG_STAT_COINCIDENCE_FLAG_MASK 0x04
#define IOREG_STAT_COINCIDENCE_FLAG_NEQ  0x00
#define IOREG_STAT_COINCIDENCE_FLAG_EQ   0x04
#define IOREG_STAT_MODE_MASK             0x03
#define IOREG_STAT_MODE_0_HBLANK         0x00
#define IOREG_STAT_MODE_1_VBLANK         0x01
#define IOREG_STAT_MODE_2_OAM_SEARCH     0x02
#define IOREG_STAT_MODE_3_DATA_XFER      0x03


#define IOREG_IF_VBLANK_BIT 0x01
#define IOREG_IF_LCDC_BIT   0x02
#define IOREG_IF_TIMER_BIT  0x04
#define IOREG_IF_SERIAL_BIT 0x08
#define IOREG_IF_PIO_BIT    0x10

#endif /* __IO_REGS_H__ */
